# Generated by Django 5.1.7 on 2025-04-03 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, verbose_name='APK')),
                ('document', models.FileField(upload_to='apk/')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'apk',
                'verbose_name_plural': 'apks',
                'db_table': '',
                'ordering': ['title'],
                'managed': True,
            },
        ),
    ]
