# Generated by Django 5.1.7 on 2025-04-04 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apk',
            name='title',
            field=models.CharField(max_length=25, verbose_name='APK'),
        ),
    ]
