# Generated by Django 5.1.7 on 2025-04-04 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apks', '0002_alter_apk_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apk',
            name='title',
            field=models.CharField(max_length=15, verbose_name='APK'),
        ),
    ]
