# Generated by Django 5.1.7 on 2025-04-23 22:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Matriz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SuperMatriz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CasoDePrueba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alcance', models.CharField(max_length=5)),
                ('fase', models.CharField(max_length=50)),
                ('caso_de_prueba', models.TextField()),
                ('estado', models.CharField(default='Por ejecutar', max_length=50)),
                ('criticidad', models.CharField(choices=[('Bloqueante', 'Bloqueante'), ('Crítico', 'Crítico')], max_length=15)),
                ('nota', models.TextField(blank=True, null=True)),
                ('matriz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='casos', to='matrix.matriz')),
            ],
        ),
        migrations.AddField(
            model_name='matriz',
            name='super_matriz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matrices', to='matrix.supermatriz'),
        ),
    ]
