# Generated by Django 5.1.7 on 2025-05-14 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrix', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketPorLevantar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tester', models.CharField(max_length=100)),
                ('ticket_SCT', models.CharField(max_length=100)),
                ('BRF', models.CharField(max_length=100)),
                ('Region', models.CharField(max_length=100)),
                ('desc', models.TextField()),
                ('prioridad', models.CharField(max_length=50)),
                ('nota', models.TextField()),
                ('super_matriz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets_por_levantar', to='matrix.supermatriz')),
            ],
        ),
        migrations.CreateModel(
            name='Validate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tester', models.CharField(max_length=100)),
                ('ticket', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('prioridad', models.CharField(max_length=50)),
                ('estado', models.CharField(max_length=50)),
                ('super_matriz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validates', to='matrix.supermatriz')),
            ],
        ),
    ]
