# Generated by Django 5.1.7 on 2025-05-14 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrix', '0002_ticketporlevantar_validate'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketporlevantar',
            name='matriz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tickets_por_levantar', to='matrix.matriz'),
        ),
        migrations.AddField(
            model_name='validate',
            name='matriz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='validates', to='matrix.matriz'),
        ),
    ]
