# Generated by Django 5.1.7 on 2025-05-14 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrix', '0003_ticketporlevantar_matriz_validate_matriz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='validate',
            name='tester',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
