# Generated by Django 5.1.7 on 2025-05-14 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrix', '0004_alter_validate_tester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='validate',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='validate',
            name='estado',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='validate',
            name='prioridad',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='validate',
            name='ticket',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
