# Generated by Django 5.1.7 on 2025-05-14 20:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrix', '0005_alter_validate_descripcion_alter_validate_estado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetallesValidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filtro_RN', models.CharField(max_length=255)),
                ('comentario_RN', models.TextField(blank=True, null=True)),
                ('super_matriz', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_validate', to='matrix.supermatriz')),
            ],
        ),
    ]
