# Generated by Django 5.1.7 on 2025-05-15 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrix', '0006_detallesvalidate'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketporlevantar',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
