# Generated by Django 5.1.7 on 2025-05-20 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrix', '0008_matriz_alcances_utilizados'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallesvalidate',
            name='filtro_RN',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
