# Generated by Django 5.1.7 on 2025-05-26 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matrix', '0009_alter_detallesvalidate_filtro_rn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketporlevantar',
            name='matriz',
        ),
    ]
