# Generated by Django 5.1.7 on 2025-05-26 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrix', '0010_remove_ticketporlevantar_matriz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketporlevantar',
            name='BRF',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
