# Generated by Django 5.1.7 on 2025-05-28 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrix', '0011_alter_ticketporlevantar_brf'),
    ]

    operations = [
        migrations.AddField(
            model_name='casodeprueba',
            name='tester',
            field=models.TextField(blank=True, null=True),
        ),
    ]
