# Generated by Django 5.1.7 on 2025-05-28 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrix', '0013_alter_ticketporlevantar_ticket_sct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketporlevantar',
            name='BRF',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ticketporlevantar',
            name='ticket_SCT',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
