# Generated by Django 5.1.7 on 2025-05-28 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrix', '0014_alter_ticketporlevantar_brf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketporlevantar',
            name='BRF',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='ticketporlevantar',
            name='desc',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='ticketporlevantar',
            name='nota',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='ticketporlevantar',
            name='ticket_SCT',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
