# Generated by Django 5.1.7 on 2025-05-29 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrix', '0016_alter_ticketporlevantar_desc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallesvalidate',
            name='super_matriz',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='matrix.supermatriz'),
        ),
    ]
