# Generated by Django 5.1.7 on 2025-05-29 20:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrix', '0017_alter_detallesvalidate_super_matriz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallesvalidate',
            name='super_matriz',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_validate', to='matrix.supermatriz'),
        ),
    ]
