# Generated by Django 5.1.7 on 2025-05-30 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrix', '0018_alter_detallesvalidate_super_matriz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallesvalidate',
            name='comentario_RN',
            field=models.TextField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='detallesvalidate',
            name='filtro_RN',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='matriz',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='supermatriz',
            name='descripcion',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='supermatriz',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='validate',
            name='tester',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
