# Generated by Django 5.1.7 on 2025-05-30 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrix', '0019_alter_detallesvalidate_comentario_rn_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casodeprueba',
            name='nota',
            field=models.TextField(blank=True, max_length=70, null=True),
        ),
    ]
