# Generated by Django 5.1.7 on 2025-03-31 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documentName', models.CharField(max_length=60, verbose_name='Documento')),
                ('document', models.FileField(upload_to='documentos/')),
                ('date', models.DateField(verbose_name='')),
            ],
            options={
                'verbose_name': 'documento',
                'verbose_name_plural': 'documentos',
                'db_table': '',
                'ordering': ['documentName'],
                'managed': True,
            },
        ),
    ]
