# Generated by Django 5.1.7 on 2025-04-01 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'managed': True, 'ordering': ['title'], 'verbose_name': 'documento', 'verbose_name_plural': 'documentos'},
        ),
        migrations.RenameField(
            model_name='document',
            old_name='documentName',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='document',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
