# Generated by Django 5.1.7 on 2025-04-01 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_alter_document_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='describe',
            field=models.CharField(max_length=120, null=True, verbose_name='Descripcion'),
        ),
    ]
