# Generated by Django 5.1.7 on 2025-04-01 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_document_describe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='describe',
            new_name='description',
        ),
    ]
